# GoReleaser config for hbactl
# https://goreleaser.com
version: 2

builds:
  - id: hbactl
    main: .
    binary: hbactl
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/hrodrig/hbactl/cmd.Version=v{{ .Version }}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

nfpms:
  - id: default
    package_name: hbactl
    file_name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    description: CLI to manage PostgreSQL pg_hba.conf safely
    vendor: "Hermes Rodríguez"
    homepage: https://github.com/hrodrig/hbactl
    license: MIT
    formats:
      - deb
      - rpm
    builds:
      - hbactl

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^test:"

# Homebrew: publish cask to tap so users can "brew install hrodrig/hbactl/hbactl"
# Create repo https://github.com/hrodrig/homebrew-hbactl first. For CI, set HOMEBREW_TAP_TOKEN (PAT with repo scope).
homebrew_casks:
  - name: hbactl
    directory: Casks
    homepage: "https://github.com/hrodrig/hbactl"
    description: "CLI to manage PostgreSQL pg_hba.conf safely"
    repository:
      owner: hrodrig
      name: homebrew-hbactl
      branch: main
    # Uncomment and set token if publishing from CI (e.g. GitHub Actions):
    # token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    url:
      verified: "github.com/hrodrig/hbactl/"
    # Remove quarantine so unsigned binary runs on macOS (optional; user can run xattr manually)
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hbactl"]
          end
